### ISSUE TITLE
HealthCheck Script : invalid path of config file

### ISSUE THREAD

**Issue by hongson1981** [k8-proxy/vmware-scripts#87]
The path of config file is invalid - it always have '/' and can not read by healthCheck script
![configFile](https://user-images.githubusercontent.com/29745336/105464723-93ec1480-5cc4-11eb-8064-9fd966ef0539.png)

**Comment by MariuszFerdyn** [comment]
It will work when you work it from bash: ./pyCheck.py

**Comment by MariuszFerdyn** [comment]
Closed a long time ago.
